import React, { useState } from 'react';
import Image from 'next/image';
import Head from 'next/head';

import TsNavbar from './components/TsNavbar';


import { Container, Table } from 'react-bootstrap';
import BridgeTable from './blg';
import Hero from './components/Hero';
import ConnectButton from './components/ConnectButton';
import Footer from './components/Footer';

export default function Home() {
  const [isConnected, setIsConnected] = useState(true);

  return (
    <div >
      <Head>
        <title>SG POLY BRIDGE</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/logo.png' />
      </Head>
      {/* <main> */}
        <TsNavbar />
        <div className='ts-main-wrapper position-relative bg-primary-gradient  min-h-100  d-flex flex-column justify-content-center align-items-end   '>
          {isConnected ? (
            <div className='w-100'>
              <Container fluid className='h-100 mb-5'>
                <div className='mw-1100 mx-auto'>
                  <Hero />
                </div>
              </Container>
              <BridgeTable />
              <Container fluid className=' my-5 text-end'>
                <Footer />
              </Container>
            </div>
          ) : (
            <div className='mw-1100 mx-auto'>
              <Container fluid className='h-100 my-4 text-center'>
                <ConnectButton />
              </Container>
            </div>
          )}
        </div>
      {/* </main> */}
      {/* <Footer /> */}
    </div>
  );
}
